# Generated by Django 4.1.6 on 2023-02-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_estudante', models.PositiveIntegerField()),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('segundo_nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('curso', models.CharField(max_length=50)),
                ('media', models.FloatField()),
            ],
        ),
    ]
